spring:
  application:
    name: jpa
management:
  context_path: /
security:
  user:
    password: password
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    # org.springframework.security: DEBUG