INSERT INTO `team5`.`amenities` (`name`) VALUES ('Animals');
INSERT INTO `team5`.`amenities` (`name`) VALUES ('Smoking');
INSERT INTO `team5`.`amenities` (`name`) VALUES ('TV');
INSERT INTO `team5`.`amenities` (`name`) VALUES ('Kitchen staff');
INSERT INTO `team5`.`amenities` (`name`) VALUES ('Children');
INSERT INTO `team5`.`amenities` (`name`) VALUES ('Parking');
INSERT INTO `team5`.`amenities` (`name`) VALUES ('For people with disabilities');
INSERT INTO `team5`.`amenities` (`name`) VALUES ('Lift');
INSERT INTO `team5`.`amenities` (`name`) VALUES ('Washing machine');
INSERT INTO `team5`.`amenities` (`name`) VALUES ('Private house');
UPDATE `team5`.`amenities` SET `name`='Wi-Fi' WHERE `id`='1';
