ALTER TABLE `roles`
  ADD COLUMN `user_id` INT NULL AFTER `name`;

ALTER TABLE `roles`
  ADD CONSTRAINT `fk_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
