DROP TRIGGER IF EXISTS `team5`.`rents_BEFORE_INSERT`;

DELIMITER $$
USE `team5`$$
CREATE DEFINER = CURRENT_USER TRIGGER `team5`.`rents_BEFORE_INSERT` BEFORE INSERT ON `rents` FOR EACH ROW
BEGIN
IF (NEW.from > NEW.to) THEN
INSERT INTO rents(`from`, `to`) VALUES (NEW.from, NEW.to);
END IF;
END$$
DELIMITER ;
